spring:
  application:
    name: suchee

  datasource:
    url: jdbc:postgresql://localhost:5434/sucheeDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
    log-flags: "all"
    enabled-flags1: all
